name: Create resourcepack zip
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      NAME: vapes-rp

    steps:
      - uses: actions/checkout@v4

      - name: Install zip
        run: |
          sudo apt update
          sudo apt install -y zip

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Read version.txt
        id: version
        run: |
          echo "VERSION=$(cat "${{ github.workspace }}/version.txt")" >> $GITHUB_OUTPUT

      - name: Substitute version placeholder
        run: find "${{ github.workspace }}" -maxdepth 1 -type f -exec sudo sed -i "s/%version%/${{ steps.version.outputs.VERSION }}/g" {} +

      - name: Compile lore
        id: compilelore
        run: echo "LORE=$(java -jar mm2json-1.0-SNAPSHOT-all.jar -f lore.txt)" >> $GITHUB_OUTPUT

      - name: Delete unnecessary directories
        run: find "${{ github.workspace }}/"* -maxdepth 0 -type d ! -name "assets" -exec sudo rm -r {} \;

      - name: Delete unnecessary files
        run: find "${{ github.workspace }}" -type f
          \( ! -name "*.png"
          -a ! -name "*.mcmeta"
          -a ! -name "*.json"
          -a ! -name "*.dat"
          -a ! -name "*.lang"
          -a ! -name "*.ttf"
          -a ! -name "*.mcfunction"
          -a ! -name "*.ogg"
          -a ! -name "*.model"
          \) -exec sudo rm {} \;

      - name: Substitute lore placeholder
        run: find "${{ github.workspace }}" -maxdepth 1 -type f -exec sudo sed -i "s/%lore%/${{ steps.compilelore.outputs.LORE }}/g" {} +

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.NAME }}-${{ steps.version.outputs.VERSION }}
          path: ${{ github.workspace }}
