name: Create resourcepack zip
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      OUT_DIR: /build
      NAME: vapes-rp

    steps:
      - uses: actions/checkout@v3

      - name: Install zip
        run: |
          sudo apt update
          sudo apt install -y zip

      - name: Read version.txt
        id: info
        run: |
          VERSION=$(cat "${{ github.workspace }}/version.txt")
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Copy files to container
        run: sudo cp -rT . "${{ env.OUT_DIR }}"

      - name: Delete unnecessary directories
        run: find "${OUT_DIR}" -type d ! -name "assets" -exec rm -r {} \;

      - name: Delete unnecessary files
        run: find "${OUT_DIR}" -type f
          \( ! -name "*.png"
          -a ! -name "*.mcmeta"
          -a ! -name "*.json"
          -a ! -name "*.dat"
          -a ! -name "*.lang"
          -a ! -name "*.ttf"
          -a ! -name "*.mcfunction"
          -a ! -name "*.ogg"
          -a ! -name "*.model"
          \) -exec rm {} \;

      - name: Substitute placeholders
        run: find "${OUT_DIR}" -maxdepth 1 -type f -exec sed -i "s/%version%/${VERSION}/g" {} +

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ env.NAME }}-${{ steps.info.outputs.VERSION }}
          path: ${{ env.OUT_DIR }}/${{ env.NAME }}-${{ steps.info.outputs.VERSION }}